export const LOGIN_REQ = "AUTH.LOGIN_REQ";
export const LOGIN_FAILURE = "AUTH.LOGIN_FAILURE";
export const LOGIN_SUCESS = "AUTH.LOGIN_SUCESS";

export const LOGOUT_REQ = "AUTH.LOGOUT_REQ";
export const LOGOUT_FAILURE = "AUTH.LOGOUT_FAILURE";
export const LOGOUT_SUCESS = "AUTH.LOGOUT_SUCESS";

    // GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    // GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    // GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    // DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    // DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    // DELETE_FAILURE: 'USERS_DELETE_FAILURE'    
};